import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { SideNavigation } from "@/app/_components/SideNavigation";

import { ItemProvide } from "./lib/ItemContext"; //  eslint-disable-line

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Foodie's Hub Billing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ItemProvide>
          <section className="grid h-screen grid-cols-[16rem_1fr] grid-rows-[auto_1fr] gap-4">
            <div></div>
            <SideNavigation />
            <div>{children}</div>
          </section>
        </ItemProvide>
      </body>
    </html>
  );
}
