import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SideNavigation } from "@/app/_components/SideNavigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Foodie's Hub Billing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="grid h-screen grid-cols-[18rem_3.5fr] grid-rows-[auto_1fr] gap-4">
          <SideNavigation />
          <div>{children}</div>
        </section>
      </body>
    </html>
  );
}
